profile: default
region: ap-northeast-1
versioning: false
default_alias: prod
clean_build: false
configuration:
  name: lambda_cookpad_recipe
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: cookpad_hot.lambda_handler
  description: lambda function for cookpad twitter bot
  timeout: 300
  memory_size: 128
