key_id: {{ env['AWS_KMS_KEY'] }}
cipher_texts:
  secret: AQECAHixfGqoXisg7imlClgIkrA6ktI122U/uqTjfTvdxF/7sgAAAU4wggFKBgkqhkiG9w0BBwagggE7MIIBNwIBADCCATAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAEkkWM5YkRdiQWnoAgEQgIIBAU/X3PXrVerJe9PaJimTtbsAmEl1xG8bIIe0+oVcLp/4WKfzdQ4KAhXLx65104RVOYdkhX4DI2dU5zLsnbDuZbACh6tgTGq5hkkJZiU3xgZHidnktaMLNyTh9Fux7x1gV+MVccOFLnntKysaCa5PsVnHI9OrGk/k4fQPITsVqKYd4saBGkXajbyQuXQ4A0C69q4O0RrKLobPS5nEy5l/zIvn+kP5IF93I0LYD9XSGqQ4a3VlMvEuPl+7p8sk0Vt3eTrlXZKZaDvQ3XB55VC21/PfxPCh0MzkaMy+CtZ+xuNc6HoIC+Fg5herhHBzO5QEYusP8SPpxo9qptynqtoEwc3J
secret_files: {}
